### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by svangsgaard** [sargue/mailgun#11] opened 2017-01-24 09:40 UTC
Hi

Thank you very much for this library.
It seems that some (all?) of your dependencies are now compiled with java 8?
I have used your library for about 2 months, but suddenly i get this error: 
java.lang.IllegalArgumentException: Class file is Java 8 but max supported is Java 7: javax/ws/rs/ApplicationPath.class in build/exploded-app/WEB-INF/lib/javax.ws.rs-api-2.1-m02.jar

To me it looks like gradle downloaded new "versions" of your dependencies and now they are compiled using java 8. I know this isn't an error in your library per se, but I don't know how to fix this. Do you?
Let me know if you need more info

Thank you in advance

**Comment by sargue** [comment] 2017-01-24 09:54
Hi. Thanks for reporting this. Even if it's not a bug in the library it certainly affects its users that are not yet on Java 8.

That jar file seems the JAX-RS API. It is a transitive dependency. I'm not sure it should target Java 8. I will look into it.

**Comment by svangsgaard** [comment] 2017-01-24 09:59
Thank you so much. We're using your library on Google Cloud, which only supports java 7 at the moment.

**Comment by sargue** [comment] 2017-01-24 10:03
Found it.

I use Jersey as JAX-RS (RESTful) client library. Up until version 2.25 it implemented JAX-RS version 2.0 which is targeted to Java 1.7 (inside Java EE 7 actually). A week ago beta version 2.26 was pushed which seems to start work on JAX-RS 2.1 implementation which targets Java EE 8 (and Java 8 language level).

I'm changing the dependency to stick with version 2.25 for the moment. Maybe it's time to create a new version using Java 8 but that should be a major version bump surely.

**Comment by sargue** [comment] 2017-01-24 10:19
I'm preparing and publishing a new release. Meanwhile I think you should be able to workaround the resolution if you put these lines in your gradle build.

    compile 'org.glassfish.jersey.core:jersey-client:2.25'
    compile 'org.glassfish.jersey.media:jersey-media-multipart:2.25'

**Comment by svangsgaard** [comment] 2017-01-24 10:28
Thank you for your quick replies. 
Unfortunately I'm still getting the same error. Should I exclude them from your library using gradle?

**Comment by sargue** [comment] 2017-01-24 10:36
As you can see I'm not very good at gradle resolution. :-)

I'm publishing 1.3.2 right now. After that I will try to research how to pin a specific version with a test project.

**Comment by svangsgaard** [comment] 2017-01-24 10:37
Thank you. I'll try 1.3.2 when it's available.

**Comment by sargue** [comment] 2017-01-24 10:38
Fixed in v1.3.2.

Available now on jCenter and on a few hours on Maven Central.

**Closed by sargue** 2017-01-24 10:38 UTC

**Comment by sargue** [comment] 2017-01-24 10:42
@svangsgaard you can fix it, meanwhile, with this on your gradle build.

```
configurations.all {
    resolutionStrategy {
        force 'org.glassfish.jersey.core:jersey-client:2.25'
        force 'org.glassfish.jersey.media:jersey-media-multipart:2.25'
    }
}
```

**Comment by svangsgaard** [comment] 2017-01-24 10:43
Ah, okay. Good to know.
But 1.3.2 works like a charm :)
Thank you for your time.
